# Generated by Django 3.2 on 2022-02-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='MFY nomi')),
                ('inspector', models.CharField(blank=True, max_length=255, null=True, verbose_name='IIB inspektori FISH')),
                ('rais', models.CharField(blank=True, max_length=255, null=True, verbose_name='MFY raisi FISH')),
                ('inspector_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon nomeri')),
                ('helper', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xokim yordamchisi FISH')),
                ('helper_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon nomeri')),
                ('leader', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yoshlar yetakchisi FISH')),
                ('leader_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon nomeri')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
            ],
        ),
    ]
