# Generated by Django 3.2 on 2022-02-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Shahar/Tuman', 'verbose_name_plural': 'Shaharlar/Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Murojaat', 'verbose_name_plural': 'Murojaatlar'},
        ),
        migrations.AlterModelOptions(
            name='mfy',
            options={'verbose_name': "Mahalla fuqarolar yig'ini", 'verbose_name_plural': "Mahalla fuqarolar yig'inlari"},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Telegram profil', 'verbose_name_plural': 'Telegram profillar'},
        ),
        migrations.AddField(
            model_name='profile',
            name='step',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_id',
            field=models.CharField(max_length=16, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram nomi (@username)'),
        ),
    ]
