# Generated by Django 3.2 on 2022-02-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_telegramchannel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='mfys_count',
            field=models.IntegerField(default=0),
        ),
    ]
