# Generated by Django 3.2 on 2022-02-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220217_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helperinfographic',
            options={'verbose_name': 'Hokim yordamchisi infogrfikasi', 'verbose_name_plural': 'Hokim yordamchisi infogrfikalari'},
        ),
        migrations.AlterModelOptions(
            name='leaderinfographic',
            options={'verbose_name': 'Yoshlar yetakchisi infografikasi', 'verbose_name_plural': 'Yoshlar yetakchisi infografikalari'},
        ),
        migrations.AlterModelOptions(
            name='telegramchannel',
            options={'verbose_name': 'Obuna telegram kanal', 'verbose_name_plural': 'Obuna telegram kanallar'},
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='chat_id',
            field=models.CharField(max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Kanal nomi'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='url',
            field=models.TextField(default='', verbose_name='Havola'),
        ),
    ]
