# Generated by Django 3.2 on 2022-02-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220217_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Hudud nomi')),
                ('cities_count', models.IntegerField(default=0, verbose_name='Tuman/shaharlar soni')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
    ]
