# Generated by Django 3.2 on 2022-02-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220220_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperinfographic',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Media Fayl'),
        ),
        migrations.AlterField(
            model_name='leaderinfographic',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Media Fayl'),
        ),
    ]
