# Generated by Django 3.2 on 2022-02-21 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220221_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperinfographic',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Video ID'),
        ),
        migrations.AddField(
            model_name='leaderinfographic',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Video ID'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Maktab nomi')),
                ('head_master', models.CharField(max_length=255, verbose_name='Direktori')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqami')),
                ('mfy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mfy')),
            ],
        ),
    ]
