# Generated by Django 3.2 on 2022-02-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220221_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfy',
            name='sector_director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sektor rahbari'),
        ),
        migrations.AddField(
            model_name='mfy',
            name='sector_director_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sektor rahbari telefon nomeri:'),
        ),
    ]
