# Generated by Django 3.2 on 2022-02-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220221_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sektor rahbari')),
                ('director_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sektor rahbari telefon nomeri:')),
            ],
            options={
                'verbose_name': 'Sektor rahbari',
                'verbose_name_plural': 'Sektor rahbarlari',
            },
        ),
        migrations.RemoveField(
            model_name='mfy',
            name='sector_director',
        ),
        migrations.RemoveField(
            model_name='mfy',
            name='sector_director_phone',
        ),
        migrations.AddField(
            model_name='mfy',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector'),
        ),
    ]
