# Generated by Django 3.2 on 2022-02-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220221_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
