# Generated by Django 3.2 on 2022-02-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220221_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='order_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='school',
            name='mfy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='core.mfy'),
        ),
    ]
