# Generated by Django 3.2 on 2022-03-03 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_auto_20220222_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='moderators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
